### ISSUE TITLE
JS build error

### ISSUE THREAD

**Issue by tmbb** [talonframework/talon_demo#1]
When I run `mix phx.server` I get this error.
I's probably a problem with brunch but I don't have time to investigate right now.

```
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
[error] Task #PID<0.392.0> started from NewAdmin.Endpoint terminating
** (stop) :watcher_command_error
    (phoenix) lib/phoenix/endpoint/watcher.ex:29: Phoenix.Endpoint.Watcher.watch/3
    (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/3
    Args: ["node", ["node_modules/.bin/brunch", "watch", "--stdin"], [cd: "c:/Users/<my-username>/Projects/elixir/new_admin_demo"]]
c:\Users\<my-username>\Projects\elixir\new_admin_demo\node_modules\.bin\brunch:2
```

**Comment by smpallen99** [comment]
I just pulled down a fresh copy of the project and it worked fine. I ran:

```
git clone ...
cd new_admin_demo
mix deps.get
npm install
mix phx.server
```
I did not do the ecto create, migrate and seeds stuff since I already had a seeded database.

I wonder if its a windows issue? I'm running on a Mac.

**Comment by smpallen99** [comment]
I'm running
node v7.9.0
npm 4.2.0

**Comment by smpallen99** [comment]
Thanks @tmbb You have the honour of being the first and first accepted PR on Talon. Thanks!!
